### ISSUE TITLE
Option to set the Zoom Unit to be additive instead of multiplicative

### ISSUE THREAD

**Issue by zaytri** [wraith13/zoombar-vscode#17]
The Zoom Unit seems to be multiplicative, so pressing the Zoom In (+) button multiplies it by that much percent, when I expected it to be additive.

## Current Functionality
- With a Zoom Unit of 10, it does this:
  - 100%
  - 110%
  - 121%
  - 133%
  - 146%
  - etc.
- With a Zoom Unit of 25, it does this:
  - 100%
  - 125%
  - 156%
  - 195%
  - 244%
  - etc.

## Expected Functionality
- With a Zoom Unit of 10:
  - 100%
  - 110%
  - 120%
  - 130%
  - 140%
  - etc.
- With a Zoom Unit of 25:
  - 100%
  - 125%
  - 150%
  - 175%
  - 200%
  - etc.

**Comment by wraith13** [comment]
I updated. How is this?

**Comment by zaytri** [comment]
That works great! Thank you!
